SET OUT_DIR=out
SET ARTICLE_URLS_FILE=links
SET OUT_DIR_BASE_FILE=index.html
SET ARTICLE_NAMES_FILE=article_names

SET CUSTOM_WEBSITE="YOUR_CUSTOM_WEBSITE"
SET LMD_M_COOKIE="YOUR_LMD_M_COOKIE"
SET LMD_S_COOKIE="YOUR_LMD_S_COOKIE"
SET ACCESS_TOKEN="YOUR_POCKET_ACCESS_TOKEN"
SET CONSUMER_KEY="YOUR_POCKET_CONSUMER_KEY"
SET SURGE_LOGIN="YOUR_SURGE_LOGIN"
SET SURGE_TOKEN="YOUR_SURGE_TOKEN"

start /w download_articles.bat
start /w upload_online.bat
start /w upload_to_pocket.bat
